# Generated by Django 5.2.5 on 2025-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_rename_imagen_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='colorvariante',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='color_principal',
            field=models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('black', 'Negro'), ('white', 'Blanco'), ('pink', 'Rosa'), ('purple', 'Púrpura')], default='red', max_length=50),
        ),
        migrations.AlterField(
            model_name='colorvariante',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('black', 'Negro'), ('white', 'Blanco'), ('pink', 'Rosa'), ('purple', 'Púrpura')], max_length=50),
        ),
    ]
