# Generated by Django 5.2.5 on 2025-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_producto_stock_colorvariante_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('mallas_enterizas', 'Mallas enterizas'), ('lenceria', 'Lencería'), ('disfraz_sexi', 'Disfraz sexi')], default='lenceria', max_length=50),
        ),
    ]
